#Tensor Operations

In [1]:
import tensorflow as tf
import numpy as np

# Check TensorFlow version
print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.18.0


In [2]:
# Creating Tensors
scalar = tf.constant(7)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2], [3, 4]])
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [3]:
print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:", matrix)
print("Tensor:", tensor)

Scalar: tf.Tensor(7, shape=(), dtype=int32)
Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Tensor: tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [4]:
# Tensor Operations
x = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
y = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

In [5]:
print("Addition:\n", tf.add(x, y))
print("Multiplication:\n", tf.multiply(x, y))
print("Matrix Multiplication:\n", tf.matmul(x, y))

Addition:
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
Multiplication:
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
Matrix Multiplication:
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [6]:
# Reshaping Tensors
reshaped_tensor = tf.reshape(tensor, [2,4])
print("Reshaped Tensor:\n", reshaped_tensor)


Reshaped Tensor:
 tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


In [7]:
# Einsum Demonstrations
# Example 1: Element-wise summation
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
einsum_result1 = tf.einsum('ij,ij->ij', a, b)
print("Einsum - Element-wise multiplication:\n", einsum_result1)

Einsum - Element-wise multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [8]:
# Example 2: Matrix Multiplication using Einsum
einsum_result2 = tf.einsum('ik,kj->ij', x, y)
print("Einsum - Matrix Multiplication:\n", einsum_result2)

Einsum - Matrix Multiplication:
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [9]:
# Example 3: Sum over specific axis
c = tf.constant([[1, 2, 3], [4, 5, 6]])
einsum_result3 = tf.einsum('ij->i', c)  # Sum across columns
print("Einsum - Sum across columns:\n", einsum_result3)

Einsum - Sum across columns:
 tf.Tensor([ 6 15], shape=(2,), dtype=int32)


In [10]:
# Example 4: Outer Product
d = tf.constant([1, 2, 3])
e = tf.constant([4, 5, 6])
einsum_result4 = tf.einsum('i,j->ij', d, e)
print("Einsum - Outer Product:\n", einsum_result4)

Einsum - Outer Product:
 tf.Tensor(
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]], shape=(3, 3), dtype=int32)


In [11]:
# Example 5: Transposing using Einsum
f = tf.constant([[1, 2], [3, 4]])
einsum_result5 = tf.einsum('ij->ji', f)
print("Einsum - Transpose:\n", einsum_result5)

Einsum - Transpose:
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
